---
output: html_document
---

```{r, message=FALSE, warning=FALSE, include=FALSE}
#source('../global.R')
```

This tab provides a short user guide how to use this web application, an overview of the core functionalities, and key references related to the main computations

Given time series of daily precipitation (RAIN, mm), minimum (AIRTMIN, ºC) and maximum temperature (AIRTMAX, ºC), and (as an option) reference evapotranspiration (ET0, mm), this tool evaluates the number of occurrences per year of extreme temperatures (heat and cold shocks) and extreme aridity.
The latter is based on the use of the Agricultural Reference Index for Drought (ARID, Woli et al., 2012), which is defined as the ratio between actual transpiration (T) and the reference evapotranspiration (ET0):

$$\mathit{ARID} = 1 - \frac{T}{\mathit{ET0}}$$

and ranges from 0 (no water deficit) to 1 (most extreme aridity, T = 0).

By providing appropriate thresholds in the tab 'Occurrence of Extreme Conditions', the following criteria can be specified by the user:

* Heat shocks: `r sprintf('$$\\mathit{AIRTMAX} > \\mathit{AIRTMAX}_\\mathit{crit} \\ \\textrm{where } \\ \\mathit{AIRTMAX}_\\mathit{crit} \\in [%.1f, %.1f] \\ ^{\\circ}\\textrm{C}$$', AIRTMAXcr.l, AIRTMAXcr.h)`

* Cold shocks: `r sprintf("$$\\mathit{AIRTMIN} < \\mathit{AIRTMIN}_\\mathit{crit} \\ \\textrm{where } \\ \\mathit{AIRTMIN}_\\mathit{crit} \\in [%.1f, %.1f] \\ ^{\\circ}\\textrm{C}$$",
            AIRTMINcr.l, AIRTMINcr.h)`
            
* Extreme aridity: `r sprintf("$$\\mathit{ARID} > \\mathit{ARID}_\\mathit{crit} \\ \\textrm{where } \\ \\mathit{ARID}_\\mathit{crit} \\in [%.1f, %.1f]$$",
            ARIDcr.l, ARIDcr.h)`
            
The criteria are evaluated with respect to the time of the year ('Start Date' – 'End Date') defined by the user in the same tab.

Input data should be provided in a CSV-file, using the same format as required by the crop modelling platform BIOMA (a sample file can be downloaded [here](TestLocation.csv)). To upload the data go to tab 'Data Upload'..

If ET0 is not provided as input, it will automatically be estimated based on Hargreaves' equation (Hargreaves and Samani, 1982). In this case, the latitude of the location of interest should be specified for the estimation of incoming solar radiation at the top of the atmosphere. Alternatively, solar radiation and ET0 can be evaluated using the tools developed by Donatelli et al. (2006a and 2006b), which are implemented in BIOMA.

To calculate the soil moisture budget (mm) and ARID (-) go to tab 'Soil Moisture Budget Computation'.

This tool can be used as a complement to ClimIndices, a software component for the evaluation of agroclimatic indicators developed by Confalonieri et al. (2010) also available through the BIOMA platform.

## Acknowledgements

This web application was developed by Tommy Klein and Pierluigi Calanca (Agroscope, Institute for Sustainability Sciences ISS) in the context of the MODEXTREME project (Modelling vegetation response to EXTREMe Events, http://modextreme.org), which has received funding from the European Community’s Seven Framework Programme-FP7 (KBBE.2013.1.4-09) under Grant Agreement No. 613817.2013-2016.

## References

Confalonieri, R., Bellocchi, G., Donatelli, M., 2010. A software component to compute agro-meteorological indicators. Environmental Modelling & Software 25, 1485-1486

Donatelli, M., Carlini, L., Bellocchi, G., 2006a. A software component for estimating solar radiation. Environmental Modelling & Software 21, 411-416

Donatelli, M., Bellocchi, G., Carlini, L., 2006b. Sharing knowledge via software components: Models on reference evapotranspiration. European Journal of Agronomy 24 (2006) 186-192

Hargreaves, G.H., Samani, Z.A., 1982. Estimating potential evapotranspiration. Journal of the Irrigation and Drainage Division 108, 225-230

Woli, P., Jones, J.W., Ingram, K.T., Fraisse, C.W., 2012. Agricultural Reference Index for Drought (ARID). Agronomy Journal 104, 287-300